// Package main is the entry point for the Clever AI Gate server.
//
// @title           Clever AI Gate API
// @version         1.0.0
// @description     High-performance AI Router & Orchestration Core. Routes requests to 1600+ AI models with sub-millisecond overhead.
// @termsOfService  https://clever-ai-gate.dev/terms
//
// @contact.name   Clever AI Gate Team
// @contact.url    https://clever-ai-gate.dev
// @contact.email  support@clever-ai-gate.dev
//
// @license.name   MIT
// @license.url    https://opensource.org/licenses/MIT
//
// @host           localhost:8080
// @BasePath       /
//
// @securityDefinitions.apikey  BearerAuth
// @in                          header
// @name                        Authorization
// @description                 Enter your API key with the "Bearer " prefix, e.g. "Bearer cag_xxxx"
package main

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/joho/godotenv"
	"github.com/redis/go-redis/v9"
	"github.com/skadraneshghn/clever-ai-gate/internal/cache"
	"github.com/skadraneshghn/clever-ai-gate/internal/cluster"
	"github.com/skadraneshghn/clever-ai-gate/internal/config"
	"github.com/skadraneshghn/clever-ai-gate/internal/credentials"
	"github.com/skadraneshghn/clever-ai-gate/internal/database"
	"github.com/skadraneshghn/clever-ai-gate/internal/health"
	"github.com/skadraneshghn/clever-ai-gate/internal/jobs"
	"github.com/skadraneshghn/clever-ai-gate/internal/proxy"
	"github.com/skadraneshghn/clever-ai-gate/internal/redisclient"
	"github.com/skadraneshghn/clever-ai-gate/internal/router"
	"github.com/skadraneshghn/clever-ai-gate/internal/telemetry"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"

	// Import generated swagger docs (will be generated by swag init)
	_ "github.com/skadraneshghn/clever-ai-gate/docs"
)

func main() {
	// Load .env file for local development (silently ignored in production)
	_ = godotenv.Load()

	// Load configuration from environment
	cfg := config.Load()

	// --- Initialize LogHub before the logger so the logger can write to it ---
	logDir := os.Getenv("LOG_DIR")
	if logDir == "" {
		logDir = "logs"
	}
	logHub, err := telemetry.NewLogHub(logDir)
	if err != nil {
		panic("failed to initialize log hub: " + err.Error())
	}
	defer logHub.Sync()

	// Initialize structured logger
	logger := initLogger(cfg.LogLevel, logHub)
	defer logger.Sync()

	logger.Info("starting Clever AI Gate",
		zap.String("mode", cfg.GinMode),
		zap.Int("port", cfg.Port),
	)

	ctx := context.Background()

	// --- Step 1: Initialize database connection pool ---
	dbPool, err := database.NewPool(ctx, cfg.DatabaseURL, logger)
	if err != nil {
		logger.Fatal("failed to connect to database", zap.Error(err))
	}
	defer dbPool.Close()

	// --- Step 2: Run database migrations ---
	if err := database.RunMigrations(ctx, dbPool, logger); err != nil {
		logger.Fatal("failed to run migrations", zap.Error(err))
	}

	// --- Step 2.5: Initialize shared Redis client (tuned for Clever Cloud) ---
	redisClient, err := redisclient.New(cfg, logger)
	if err != nil {
		// Redis is not required — log and continue without it
		logger.Warn("redis initialization failed, running without Redis", zap.Error(err))
		redisClient = nil
	}
	if redisClient != nil {
		defer redisClient.Close()
	}

	// Extract the raw *redis.Client for subsystems that need it directly
	var rdb interface{ Unwrap() interface{ LPush(ctx context.Context, key string, values ...interface{}) interface{ Err() error } } }
	_ = rdb // placeholder — subsystems use redisClient.Unwrap() directly

	// --- Step 3: Initialize encryption vault ---
	vault, err := credentials.NewVault(cfg.MasterEncryptionKey)
	if err != nil {
		logger.Fatal("failed to initialize encryption vault", zap.Error(err))
	}

	// --- Step 4: Initialize Ristretto cache ---
	cacheStore, err := cache.New(cfg, logger)
	if err != nil {
		logger.Fatal("failed to initialize cache", zap.Error(err))
	}
	defer cacheStore.Close()

	// --- Step 4.5: Initialize two-layer tenant cache (L1=Ristretto, L2=Redis) ---
	var tenantCache *cache.RedisTenantCache
	if redisClient != nil {
		tenantCache = cache.NewRedisTenantCache(cacheStore, redisClient.Unwrap(), logger)
		logger.Info("redis tenant L2 cache enabled")
	}

	// --- Step 4.6: Initialize Redis Cache Manager (L2 for pools/models/providers) ---
	var rawRedisForCache *redis.Client
	if redisClient != nil {
		rawRedisForCache = redisClient.Unwrap()
	}
	redisCacheMgr := cache.NewRedisCacheManager(rawRedisForCache, logger)

	// --- Step 5: Load routing pools from DB → cache (+ pre-warm Redis L2) ---
	syncManager := credentials.NewSyncManager(dbPool, cacheStore, vault, logger)
	syncManager.SetRedisCacheManager(redisCacheMgr) // attach before LoadInitialState for pre-warming
	if err := syncManager.LoadInitialState(ctx); err != nil {
		logger.Fatal("failed to load initial routing state", zap.Error(err))
	}

	// --- Step 5.5: Subscribe to Redis cache sync events ---
	// When any cluster node publishes an invalidation event (after pool/credential mutation),
	// this node clears its Ristretto L1 so the next request re-reads fresh data from Redis L2.
	redisCacheMgr.SubscribeCacheSync(func() {
		logger.Info("[CacheSync] Received remote invalidation — reloading local routing state")
		reloadCtx, reloadCancel := context.WithTimeout(context.Background(), 15*time.Second)
		defer reloadCancel()
		if err := syncManager.LoadInitialState(reloadCtx); err != nil {
			logger.Error("[CacheSync] Failed to reload state after remote invalidation", zap.Error(err))
		}
	})
	defer redisCacheMgr.Stop()

	// --- Step 6: Start LISTEN/NOTIFY watcher ---
	syncManager.StartListener()
	defer syncManager.Stop()

	// --- Step 6.5: Initialize cluster broadcaster for cross-node cooldown sync ---
	var broadcaster *cluster.Broadcaster
	if redisClient != nil {
		broadcaster = cluster.New(redisClient.Unwrap(), logger)
		// Wrap GetPoolForCluster so it satisfies the broadcaster's interface
		broadcaster.StartSubscriber(func(pattern string) cluster.PenalizerPool {
			return syncManager.GetPoolForCluster(pattern)
		})
		defer broadcaster.Stop()
		logger.Info("cluster broadcaster started — cross-node key cooldowns active")
	}

	// --- Step 7: Start telemetry pipeline ---
	var rawRedis *redis.Client
	if redisClient != nil {
		rawRedis = redisClient.Unwrap()
	}
	telemetryPipeline := telemetry.NewPipeline(
		dbPool, logger,
		cfg.TelemetryQueueSize,
		cfg.TelemetryBatchSize,
		cfg.TelemetryFlushInterval,
		rawRedis,
	)
	telemetryPipeline.Start()
	if rawRedis != nil {
		telemetryPipeline.StartRedisConsumer()
	}
	defer telemetryPipeline.Stop()

	// --- Step 7.5: Initialize key failover telemetry AlertManager ---
	var alertSupervisor *telemetry.AlertManager
	if rawRedis != nil {
		webhookURL := os.Getenv("TELEMETRY_ALERT_WEBHOOK")
		alertSupervisor = telemetry.NewAlertManager(
			rawRedis,
			10,              // Threshold: 10 failovers
			2*time.Minute,   // Rolling Window: 2 minutes
			15*time.Minute,  // Cooldown / lock window: 15 minutes
			webhookURL,
		)
		logger.Info("failover alert manager initialized", zap.String("webhook", webhookURL))
	}

	// --- Step 8: Build HTTP transport and proxy handler ---
	transport, edgeProber := proxy.BuildOptimizedTransport(cfg, logger)
	httpClient := proxy.BuildHTTPClient(transport)
	proxyHandler := proxy.NewHandler(httpClient, cacheStore, redisCacheMgr, logger, telemetryPipeline, broadcaster, alertSupervisor)

	// Start edge IP probing and connection pre-warming
	edgeProber.Start()
	edgeProber.StartPreWarming(httpClient)

	// --- Step 9: Initialize health handler ---
	healthHandler := health.New(dbPool)

	// --- Step 9.5: Initialize Job Scheduler ---
	var jobScheduler *jobs.Scheduler
	jobScheduler, err = jobs.NewScheduler(dbPool, rawRedis, vault, logger)
	if err != nil {
		logger.Warn("failed to initialize job scheduler, jobs disabled", zap.Error(err))
		jobScheduler = nil
	} else {
		if err := jobScheduler.Start(ctx); err != nil {
			logger.Warn("failed to start job scheduler", zap.Error(err))
			jobScheduler = nil
		} else {
			defer jobScheduler.Stop()
			logger.Info("job scheduler started")
		}
	}

	// --- Step 10: Build Gin engine with all routes ---
	engine := router.NewEngine(&router.Dependencies{
		Config:        cfg,
		DB:            dbPool,
		Cache:         cacheStore,
		TenantCache:   tenantCache,
		Redis:         redisClient,
		RedisCacheMgr: redisCacheMgr,
		Vault:         vault,
		Logger:        logger,
		Health:        healthHandler,
		Proxy:         proxyHandler,
		LogHub:        logHub,
		Scheduler:     jobScheduler,
	})

	// --- Step 11: Start HTTP server ---
	srv := &http.Server{
		Addr:              fmt.Sprintf("0.0.0.0:%d", cfg.Port),
		Handler:           engine,
		ReadHeaderTimeout: 10 * time.Second,
		WriteTimeout:      0, // Disabled for streaming — context handles timeouts
		IdleTimeout:       120 * time.Second,
		MaxHeaderBytes:    1 << 20, // 1MB max header size
	}

	// Mark as ready
	healthHandler.SetReady(true)

	// Start server in goroutine
	go func() {
		logger.Info("server listening", zap.String("addr", srv.Addr))
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			logger.Fatal("server failed", zap.Error(err))
		}
	}()

	// --- Step 12: Graceful shutdown ---
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	sig := <-quit

	logger.Info("shutdown signal received", zap.String("signal", sig.String()))

	// Mark as not ready (load balancer stops sending traffic)
	healthHandler.SetReady(false)

	// Give in-flight requests time to complete
	shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer shutdownCancel()

	if err := srv.Shutdown(shutdownCtx); err != nil {
		logger.Error("server forced to shutdown", zap.Error(err))
	}

	// Stop edge probing and connection pre-warming
	edgeProber.Stop()

	logger.Info("server stopped gracefully")
}

// initLogger creates a production-tuned zap logger that dual-writes to stdout and logHub.
func initLogger(level string, logHub *telemetry.LogHub) *zap.Logger {
	var stdoutLevel zapcore.Level
	switch level {
	case "debug":
		stdoutLevel = zapcore.DebugLevel
	case "warn":
		stdoutLevel = zapcore.WarnLevel
	case "error":
		stdoutLevel = zapcore.ErrorLevel
	default:
		stdoutLevel = zapcore.InfoLevel
	}

	fileLevel := stdoutLevel
	if fileLevel > zapcore.InfoLevel {
		fileLevel = zapcore.InfoLevel
	}

	encoderCfg := zap.NewProductionEncoderConfig()
	encoderCfg.TimeKey = "timestamp"
	encoderCfg.EncodeTime = zapcore.ISO8601TimeEncoder
	encoderCfg.EncodeLevel = zapcore.LowercaseLevelEncoder
	jsonEncoder := zapcore.NewJSONEncoder(encoderCfg)

	stdoutCore := zapcore.NewCore(
		jsonEncoder,
		zapcore.Lock(os.Stdout),
		stdoutLevel,
	)

	hubCore := zapcore.NewCore(
		jsonEncoder,
		logHub,
		fileLevel,
	)

	core := zapcore.NewTee(stdoutCore, hubCore)

	return zap.New(core,
		zap.AddCaller(),
		zap.AddStacktrace(zapcore.ErrorLevel),
	)
}
