// Package main is the entry point for the Clever AI Gate server.
//
// @title           Clever AI Gate API
// @version         1.0.0
// @description     High-performance AI Router & Orchestration Core. Routes requests to 1600+ AI models with sub-millisecond overhead.
// @termsOfService  https://clever-ai-gate.dev/terms
//
// @contact.name   Clever AI Gate Team
// @contact.url    https://clever-ai-gate.dev
// @contact.email  support@clever-ai-gate.dev
//
// @license.name   MIT
// @license.url    https://opensource.org/licenses/MIT
//
// @host           localhost:8080
// @BasePath       /
//
// @securityDefinitions.apikey  BearerAuth
// @in                          header
// @name                        Authorization
// @description                 Enter your API key with the "Bearer " prefix, e.g. "Bearer cag_xxxx"
package main

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/joho/godotenv"
	"github.com/skadraneshghn/clever-ai-gate/internal/cache"
	"github.com/skadraneshghn/clever-ai-gate/internal/config"
	"github.com/skadraneshghn/clever-ai-gate/internal/credentials"
	"github.com/skadraneshghn/clever-ai-gate/internal/database"
	"github.com/skadraneshghn/clever-ai-gate/internal/health"
	"github.com/skadraneshghn/clever-ai-gate/internal/proxy"
	"github.com/skadraneshghn/clever-ai-gate/internal/router"
	"github.com/skadraneshghn/clever-ai-gate/internal/telemetry"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"

	// Import generated swagger docs (will be generated by swag init)
	_ "github.com/skadraneshghn/clever-ai-gate/docs"
)

func main() {
	// Load .env file for local development (silently ignored in production)
	_ = godotenv.Load()

	// Load configuration from environment
	cfg := config.Load()

	// --- Initialize LogHub before the logger so the logger can write to it ---
	// The log directory defaults to "logs/" relative to the working directory
	// but can be overridden by the LOG_DIR environment variable.
	logDir := os.Getenv("LOG_DIR")
	if logDir == "" {
		logDir = "logs"
	}
	logHub, err := telemetry.NewLogHub(logDir)
	if err != nil {
		// This is a startup-time error — we cannot log it yet, so panic.
		panic("failed to initialize log hub: " + err.Error())
	}
	defer logHub.Sync()

	// Initialize structured logger (dual-writes to stdout + daily log file)
	logger := initLogger(cfg.LogLevel, logHub)
	defer logger.Sync()

	logger.Info("starting Clever AI Gate",
		zap.String("mode", cfg.GinMode),
		zap.Int("port", cfg.Port),
	)

	ctx := context.Background()

	// --- Step 1: Initialize database connection pool ---
	dbPool, err := database.NewPool(ctx, cfg.DatabaseURL, logger)
	if err != nil {
		logger.Fatal("failed to connect to database", zap.Error(err))
	}
	defer dbPool.Close()

	// --- Step 2: Run database migrations ---
	if err := database.RunMigrations(ctx, dbPool, logger); err != nil {
		logger.Fatal("failed to run migrations", zap.Error(err))
	}

	// --- Step 3: Initialize encryption vault ---
	vault, err := credentials.NewVault(cfg.MasterEncryptionKey)
	if err != nil {
		logger.Fatal("failed to initialize encryption vault", zap.Error(err))
	}

	// --- Step 4: Initialize Ristretto cache ---
	cacheStore, err := cache.New(cfg, logger)
	if err != nil {
		logger.Fatal("failed to initialize cache", zap.Error(err))
	}
	defer cacheStore.Close()

	// --- Step 5: Load routing pools from DB → cache ---
	syncManager := credentials.NewSyncManager(dbPool, cacheStore, vault, logger)
	if err := syncManager.LoadInitialState(ctx); err != nil {
		logger.Fatal("failed to load initial routing state", zap.Error(err))
	}

	// --- Step 6: Start LISTEN/NOTIFY watcher ---
	syncManager.StartListener()
	defer syncManager.Stop()

	// --- Step 7: Start telemetry pipeline ---
	telemetryPipeline := telemetry.NewPipeline(
		dbPool, logger,
		cfg.TelemetryQueueSize,
		cfg.TelemetryBatchSize,
		cfg.TelemetryFlushInterval,
	)
	telemetryPipeline.Start()
	defer telemetryPipeline.Stop()

	// --- Step 8: Build HTTP transport and proxy handler ---
	transport := proxy.BuildOptimizedTransport(cfg)
	httpClient := proxy.BuildHTTPClient(transport)
	proxyHandler := proxy.NewHandler(httpClient, cacheStore, logger)

	// --- Step 9: Initialize health handler ---
	healthHandler := health.New(dbPool)

	// --- Step 10: Build Gin engine with all routes ---
	engine := router.NewEngine(&router.Dependencies{
		Config: cfg,
		DB:     dbPool,
		Cache:  cacheStore,
		Vault:  vault,
		Logger: logger,
		Health: healthHandler,
		Proxy:  proxyHandler,
		LogHub: logHub,
	})

	// --- Step 11: Start HTTP server ---
	srv := &http.Server{
		Addr:              fmt.Sprintf("0.0.0.0:%d", cfg.Port),
		Handler:           engine,
		ReadHeaderTimeout: 10 * time.Second,
		WriteTimeout:      0, // Disabled for streaming — context handles timeouts
		IdleTimeout:       120 * time.Second,
		MaxHeaderBytes:    1 << 20, // 1MB max header size
	}

	// Mark as ready
	healthHandler.SetReady(true)

	// Start server in goroutine
	go func() {
		logger.Info("server listening", zap.String("addr", srv.Addr))
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			logger.Fatal("server failed", zap.Error(err))
		}
	}()

	// --- Step 12: Graceful shutdown ---
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	sig := <-quit

	logger.Info("shutdown signal received", zap.String("signal", sig.String()))

	// Mark as not ready (health check will fail, load balancer stops sending traffic)
	healthHandler.SetReady(false)

	// Give in-flight requests time to complete
	shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer shutdownCancel()

	if err := srv.Shutdown(shutdownCtx); err != nil {
		logger.Error("server forced to shutdown", zap.Error(err))
	}

	logger.Info("server stopped gracefully")
}

// initLogger creates a production-tuned zap logger that dual-writes to:
//  1. os.Stdout — respects LOG_LEVEL for container log aggregators
//  2. logHub — always captures Info level minimum regardless of LOG_LEVEL,
//     so the daily rotating log file always contains the full request audit
//     trail needed to diagnose API instability (e.g. Kilo Code 500 loops).
//
// The JSON encoder uses ISO 8601 timestamps. Caller info is included so every
// log line carries its source file and line number.
func initLogger(level string, logHub *telemetry.LogHub) *zap.Logger {
	var stdoutLevel zapcore.Level
	switch level {
	case "debug":
		stdoutLevel = zapcore.DebugLevel
	case "warn":
		stdoutLevel = zapcore.WarnLevel
	case "error":
		stdoutLevel = zapcore.ErrorLevel
	default:
		stdoutLevel = zapcore.InfoLevel
	}

	// The file always captures Debug when LOG_LEVEL=debug, but is floored at
	// Info otherwise — never silenced below Info even in production.
	fileLevel := stdoutLevel
	if fileLevel > zapcore.InfoLevel {
		fileLevel = zapcore.InfoLevel
	}

	encoderCfg := zap.NewProductionEncoderConfig()
	encoderCfg.TimeKey = "timestamp"
	encoderCfg.EncodeTime = zapcore.ISO8601TimeEncoder
	encoderCfg.EncodeLevel = zapcore.LowercaseLevelEncoder
	jsonEncoder := zapcore.NewJSONEncoder(encoderCfg)

	// Core 1: stdout — uses LOG_LEVEL so operators control console noise
	stdoutCore := zapcore.NewCore(
		jsonEncoder,
		zapcore.Lock(os.Stdout),
		stdoutLevel,
	)

	// Core 2: LogHub (daily file + live SSE broadcast)
	// Always floored at Info so request/response logs are always on disk.
	hubCore := zapcore.NewCore(
		jsonEncoder,
		logHub,
		fileLevel,
	)

	core := zapcore.NewTee(stdoutCore, hubCore)

	return zap.New(core,
		zap.AddCaller(),
		zap.AddStacktrace(zapcore.ErrorLevel),
	)
}
